attributes:
  BuildIndependentTargetsInParallel: '1'
  LastSwiftUpdateCheck: '1320'
  LastUpgradeCheck: '1320'
configs:
  Debug: debug
  Release: release
name: Sample
options:
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
settings:
  configs:
    Debug:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++17
      IPHONEOS_DEPLOYMENT_TARGET: '15.2'
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++17
      IPHONEOS_DEPLOYMENT_TARGET: '15.2'
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  Sample:
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: Sample/Info.plist
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIMainStoryboardFile: Main
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: github.com.seka.playgroundswift.Sample
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_FILE: Sample/Info.plist
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
          INFOPLIST_KEY_UIMainStoryboardFile: Main
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
            UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: github.com.seka.playgroundswift.Sample
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
    sources:
    - name: Sample
      path: Sample
    type: application
  SampleTests:
    dependencies:
    - target: Sample
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '15.2'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: github.com.seka.playgroundswift.SampleTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/Sample.app/Sample
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '15.2'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: github.com.seka.playgroundswift.SampleTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/Sample.app/Sample
    sources:
    - name: SampleTests
      path: SampleTests
    type: bundle.unit-test
  SampleUITests:
    dependencies:
    - target: Sample
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: github.com.seka.playgroundswift.SampleUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: Sample
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: '1.0'
          PRODUCT_BUNDLE_IDENTIFIER: github.com.seka.playgroundswift.SampleUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: Sample
    sources:
    - name: SampleUITests
      path: SampleUITests
    type: bundle.ui-testing
